---
- name: "Check that all resources have been removed"
  shell: oc get secret,svc,pvc,route,dc,pod,is --selector="app in ({{ application_name }},{{ postgres_name }})" 2>&1
  register: result
  retries: 50
  delay: 10
  failed_when:
    - '"No resources found." not in result.stdout'
  until: '"No resources found." in result.stdout'
