---

# Instead of testing that the deployment config is removed, we test that the pods
# are cleaned up afterwards
- name: Check that all pods have been removed
  shell: oc get pods --namespace={{ namespace }} --selector="deploymentconfig in (keycloak,postgres)" 2>&1
  register: result
  retries: 50
  delay: 10
  failed_when:
    - '"No resources found." not in result.stdout'
  until: '"No resources found." in result.stdout'

- name: Check that the keycloak route has been removed
  shell: oc get route --namespace={{ namespace }} {{ keycloak_route_name }} 2>&1
  register: result
  retries: 50
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'

- name: Check that all services have been removed
  shell: oc get service --namespace={{ namespace }} {{ item }} 2>&1
  register: result
  retries: 50
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'
  with_items:
    - '{{ keycloak_service_name }}'
    - '{{ postgres_service_name }}'

- name: Check that all secrets have been removed
  shell: oc get secret --namespace={{ namespace }} {{ item }} 2>&1
  register: result
  retries: 50
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'
  with_items:
    - '{{ keycloak_secret_name }}'
    - '{{ postgres_secret_name }}'

- name: Check that all persistent volume claims have been removed
  shell: oc get pvc --namespace={{ namespace }} {{ item }} 2>&1
  register: result
  retries: 50
  delay: 10
  failed_when:
    - '"not found" not in result.stdout'
  until: '"not found" in result.stdout'
  with_items:
  - '{{ keycloak_pv_claim_name }}'
  - '{{ postgres_service_name }}'
