- name: "Generate keycloak auth token"
  uri:
    url: "{{ _apb_provision_creds.internal_keycloak_uri }}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body: "client_id=admin-cli&username={{ _apb_provision_creds.admin_username }}&password={{ _apb_provision_creds.admin_password }}&grant_type=password"
    validate_certs: no
  register: keycloak_auth_response
  until: keycloak_auth_response.status == 200
  retries: 100
  delay: 2

- name: "Create {{ service_name }} client in realm {{ namespace }}"
  uri:
    url: "{{ _apb_provision_creds.internal_keycloak_uri }}/auth/admin/realms/{{ namespace }}/clients"
    method: POST
    body: "{\"id\": \"{{ namespace }}-{{ service_name }}\", \"redirectUris\": [\"{{ redirect_uris }}\"], \"publicClient\": true }"
    validate_certs: no
    body_format: json
    headers:
      Authorization: "bearer {{ keycloak_auth_response.json.access_token }}"
    status_code: 201

- name: Encode {{ service_name }} credentials
  asb_encode_binding:
    fields:
      SSO_REALM: "{{ namespace }}"
      SSO_CLIENT: "{{ namespace }}-{{ service_name }}"
      SSO_URL: "{{ _apb_provision_creds.external_keycloak_uri }}/auth"
