---
- name: Process ImageStream from template
  template:
    src: keycloak-is.yml.j2
    dest: "/tmp/keycloak/keycloak-is.yml"
  register: is

- name: Create ImageStream
  openshift_v1_image_stream:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present
    src: "{{ is.dest | default(is.path) }}"

- name: Process DeploymentConfig from template
  template:
    src: keycloak-dc.yml.j2
    dest: "/tmp/keycloak/keycloak-dc.yml"
  register: dc

- name: Create DeploymentConfig
  openshift_v1_deployment_config:
    name: "{{ application_name }}"
    namespace: "{{ namespace}}"
    state: present
    src: "{{ dc.dest | default(dc.path) }}"

- name: Create keycloak service
  k8s_v1_service:
    name: '{{ application_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: '{{ application_name }}'
      service: '{{ application_name }}'
    selector:
      app: '{{ application_name }}'
      service: '{{ application_name }}'
    ports:
    - name: web
      port: 80
      target_port: 8080

- name: Create keycloak https route
  openshift_v1_route:
    name: '{{ application_name }}'
    namespace: '{{ namespace }}'
    labels:
      app: '{{ application_name }}'
      service: '{{ application_name }}'
    tls_termination: edge
    tls_insecure_edge_termination_policy: Redirect
    to_name: '{{ application_name }}'
    spec_port_target_port: web
  register: keycloak_route_raw

- name: Set keycloak uri from route
  set_fact:
    keycloak_uri: 'https://{{ keycloak_route_raw.route.spec.host }}'
  when: keycloak_uri is not defined
