---
- name: [POSTGRES] Deploy
  include_tasks: provision-postgres.yml
  when: _apb_plan_id == 'persistent'

- name: [KEYCLOAK] Deploy
  include_tasks: deploy-keycloak.yml
  when: _apb_plan_id != 'external'

- name: [KEYCLOAK] Provision
  include_tasks: provision-keycloak.yml
